name: Django CI/CD Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations (SQLite)
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Tests
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Starting deployment"

            cd /fahim-django/

            git fetch origin
            git checkout master
            git pull origin master

            # Ensure virtual environment exists and activate it
            if [ ! -d "venv" ]; then
                python3 -m venv venv
            fi
            source venv/bin/activate

            # Upgrade pip and install dependencies
            python -m pip install --upgrade pip
            pip install -r requirements.txt

            # Run migrations and collect static files
            python manage.py migrate
            python manage.py collectstatic --noinput

            # Ensure mod_wsgi points to correct Python (optional if compiled manually)
            # echo "LoadModule wsgi_module $(venv)/lib/python3.12/site-packages/mod_wsgi/server/mod_wsgi-py312.so" | sudo tee /etc/apache2/mods-available/wsgi.load

            # Restart Apache
            sudo systemctl restart apache2

            echo "✅ Deployment Completed Successfully"
